# Generated by Django 3.0.8 on 2020-07-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200711_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='default_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.Categories'),
        ),
    ]
