# Generated by Django 3.1.3 on 2021-02-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='file',
            new_name='path',
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
