# Generated by Django 3.1.3 on 2021-02-26 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210226_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='path',
            new_name='file',
        ),
    ]
